### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by alexgleason** [blakeembrey/universal-base64#19]
I'm using this library in a browser, to decode an hmac signature in base64.

```js
// This line crashes:
const sig = decode("s11AVt9BuoYTNNOSS8oS9TzUeh0");

const bytes = new TextEncoder().encode(sig);

const verified = await crypto.subtle.verify(
  "HMAC",
  key,
  signature,
  bytes,
);
```

The result:

```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at decode2 (index.js:67:14)
    at decodeAndVerifyUrl (index.js:83:62)
    at Object.handleFetch [as fetch] (index.js:131:23) {
  stack: URIError: URI malformed
    at decodeURIComponent …t Object.handleFetch [as fetch] (index.js:131:23),
  message: URI malformed
}
```

Also, curious if I'm doing this all wrong and you know an easier way to get a base64 signature into raw bytes.

**Comment by blakeembrey** [comment]
This library converts a string to a string, I'd just use this directly instead: https://github.com/borderless/base64. It converts between `ArrayBuffer` directly so no need to encode/decode, which should eliminate this bug too.
